import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { LoggedOut, LoggedIn } from '@/app/_components/header'
import Footer from '@/app/_components/Footer'
import isLogged from '@/lib/isLogged'

const inter = Inter({ subsets: ['latin'] })

export const revalidate = 3600

export const metadata: Metadata = {
  title: 'HMSoft',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {isLogged() ? <LoggedIn/> : <LoggedOut />}
        <main className='min-h-screen py-10'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
